export const seedDatabase = {
  permissions: [
    { id: "perm-all", scope: "*", name: "كل الصلاحيات" },
    { id: "perm-dashboard-view", scope: "dashboard:view", name: "عرض لوحة المتابعة" },
    { id: "perm-employees-view", scope: "employees:view", name: "عرض الموظفين" },
    { id: "perm-employees-write", scope: "employees:write", name: "إضافة وتعديل الموظفين" },
    { id: "perm-users-manage", scope: "users:manage", name: "إدارة المستخدمين" },
    { id: "perm-attendance-manage", scope: "attendance:manage", name: "إدارة الحضور" },
    { id: "perm-attendance-self", scope: "attendance:self", name: "تسجيل بصمة الموظف" },
    { id: "perm-requests-approve", scope: "requests:approve", name: "اعتماد الطلبات" },
    { id: "perm-org-manage", scope: "organization:manage", name: "إدارة الهيكل الإداري" },
    { id: "perm-reports-export", scope: "reports:export", name: "تصدير التقارير" },
    { id: "perm-hr-operations", scope: "hr:operations", name: "لوحة عمليات الموارد البشرية" },
    { id: "perm-organization-manage", scope: "organization:manage", name: "إدارة هيكل الإدارة والفرق" },
    { id: "perm-team-dashboard", scope: "team:dashboard", name: "لوحة الفريق للمدير المباشر" },
    { id: "perm-disputes-escalate", scope: "disputes:escalate", name: "تصعيد الشكاوى للسكرتير والتنفيذي" },
    { id: "perm-reports-pdf", scope: "reports:pdf", name: "تصدير تقارير PDF/HTML" },
    { id: "perm-reports-excel", scope: "reports:excel", name: "تصدير تقارير Excel/CSV" },
    { id: "perm-attendance-risk", scope: "attendance:risk", name: "مركز تقييم خطر البصمة" },
    { id: "perm-decisions-manage", scope: "decisions:manage", name: "إدارة سجل القرارات الإدارية" },
    { id: "perm-decisions-acknowledge", scope: "decisions:acknowledge", name: "تأكيد الاطلاع على القرارات" },
    { id: "perm-disputes-minutes", scope: "disputes:minutes", name: "محاضر لجنة حل الخلافات" },
    { id: "perm-reports-monthly-pdf-auto", scope: "reports:monthly-pdf-auto", name: "تقارير PDF شهرية تلقائية" },
    { id: "perm-settings-manage", scope: "settings:manage", name: "إدارة الإعدادات" },
    { id: "perm-audit-view", scope: "audit:view", name: "عرض سجل التدقيق" },
    { id: "perm-kpi-manage", scope: "kpi:manage", name: "إدارة تقييمات الأداء كاملة" },
    { id: "perm-kpi-team", scope: "kpi:team", name: "اعتماد تقييمات الفريق المباشر" },
    { id: "perm-kpi-self", scope: "kpi:self", name: "تقييم ذاتي للموظف" },
    { id: "perm-disputes-manage", scope: "disputes:manage", name: "إدارة الشكاوى وفض الخلافات" },
    { id: "perm-location-view", scope: "location:view_all", name: "عرض مواقع الموظفين" },
    { id: "perm-offline-manage", scope: "offline:manage", name: "إدارة المزامنة دون اتصال" },
    { id: "perm-access-control-manage", scope: "access_control:manage", name: "تكامل البوابات والأجهزة" },
    { id: "perm-ai-view", scope: "ai:view", name: "عرض تحليلات الذكاء الاصطناعي" },
    { id: "perm-integrations-manage", scope: "integrations:manage", name: "إدارة التكاملات" },
    { id: "perm-realtime-view", scope: "realtime:view", name: "عرض اللوحة اللحظية" },
    { id: "perm-attendance-review", scope: "attendance:review", name: "مراجعة البصمات المرفوضة" },
    { id: "perm-devices-manage", scope: "devices:manage", name: "إدارة الأجهزة المعتمدة" },
    { id: "perm-security-view", scope: "security:view", name: "عرض سجل الأمان" },
  ],
  roles: [
    { id: "role-admin", name: "مدير النظام", key: "ADMIN", slug: "admin", description: "صلاحيات كاملة", permissions: ["*"] },
    { id: "role-executive", name: "المدير التنفيذي", key: "EXECUTIVE", slug: "executive", description: "متابعة تنفيذية وقرارات حساسة بدون أدوات الأدمن التقنية", permissions: ["dashboard:view","employees:view","reports:export","executive:report","executive:mobile","executive:presence-map","live-location:request","attendance:risk","decisions:manage","reports:monthly-pdf-auto","disputes:minutes","sensitive-actions:approve","approvals:manage","alerts:manage","control-room:view","daily-report:review","kpi:executive","kpi:final-approve"] },
    { id: "role-executive-secretary", name: "السكرتير التنفيذي والتقني", key: "EXECUTIVE_SECRETARY", slug: "executive-secretary", description: "صلاحيات كاملة على النظام مع متابعة تنفيذية وتقنية", permissions: ["*"] },
    { id: "role-hr", name: "مدير موارد بشرية", key: "HR_MANAGER", slug: "hr-manager", description: "صلاحيات موارد بشرية فقط بدون إعدادات تقنية", permissions: ["dashboard:view","employees:view","employees:write","users:manage","attendance:manage","attendance:review","attendance:rules","attendance:smart","requests:approve","leave:balance","documents:manage","reports:export","kpi:hr","kpi:monthly","kpi:manage","daily-report:review","disputes:committee","disputes:manage","disputes:minutes","notifications:manage","decisions:manage","attendance:risk","reports:monthly-pdf-auto"] },
    { id: "role-manager", name: "مدير مباشر", key: "DIRECT_MANAGER", slug: "direct-manager", description: "يرى فريقه المباشر فقط ويعتمد تقييماتهم", permissions: ["dashboard:view","employees:view","manager:team","manager:suite","attendance:manage","requests:approve","reports:export","kpi:team","daily-report:review","disputes:manage","realtime:view","manager:team-only","decisions:acknowledge"] },
    { id: "role-employee", name: "موظف", key: "EMPLOYEE", slug: "employee", description: "يرى بياناته وبصماته وتقييمه الذاتي فقط", permissions: ["dashboard:view","attendance:self","kpi:self","disputes:create","location:self","tasks:self","documents:self","requests:self","daily-report:self","action-center:self","live-location:respond","decisions:acknowledge"] },
  ],
  governorates: [
    { id: "gov-giza", code: "GIZ", name: "الجيزة", latitude: 29.950738592862045, longitude: 31.238094542328678, active: true },
  ],
  complexes: [
    { id: "cx-ahla-manil", code: "CX-AHLA-MANIL", name: "مجمع منيل شيحة", governorateId: "gov-giza", branchId: "b-ahla-manil", address: "شارع مزلقان العرب, Manil Shihah, Abu El Numrus, Giza Governorate 12912", latitude: 29.950738592862045, longitude: 31.238094542328678, radiusMeters: 180, maxAccuracyMeters: 90, managerEmployeeId: "emp-executive-director", active: true },
  ],
  branches: [
    { id: "b-ahla-manil", code: "AHLA-MANIL", name: "مجمع منيل شيحة", governorateId: "gov-giza", complexId: "cx-ahla-manil", address: "شارع مزلقان العرب, Manil Shihah, Abu El Numrus, Giza Governorate 12912", latitude: 29.950738592862045, longitude: 31.238094542328678, radiusMeters: 180, geofenceRadiusMeters: 180, maxAccuracyMeters: 90, managerEmployeeId: "emp-executive-director", active: true },
  ],
  departments: [
    {
        "id": "d-executive",
        "code": "EXEC",
        "name": "الإدارة التنفيذية",
        "branchId": "b-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "description": "المدير التنفيذي والسكرتارية التنفيذية",
        "active": true
    },
    {
        "id": "d-field-management",
        "code": "MGT",
        "name": "الإشراف والمديرون المباشرون",
        "branchId": "b-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "description": "المديرون المباشرون التابعون للمدير التنفيذي",
        "active": true
    },
    {
        "id": "d-field-operations",
        "code": "OPS",
        "name": "فرق التشغيل والخدمات",
        "branchId": "b-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-03",
        "description": "الموظفون والفرق التابعة للمديرين المباشرين",
        "active": true
    },
    {
        "id": "d-hr",
        "code": "HR",
        "name": "الموارد البشرية",
        "branchId": "b-ahla-manil",
        "managerEmployeeId": "emp-executive-secretary",
        "description": "شؤون العاملين والتقييمات والحضور",
        "active": true
    }
],
  shifts: [],
  employees: [
    {
        "id": "emp-executive-director",
        "employeeCode": "AHS-001",
        "fullName": "الشيخ محمد يوسف",
        "phone": "PHONE_PLACEHOLDER_010",
        "email": "emp.demo010@ahla.local",
        "photoUrl": "employee-avatars/emp-executive-director.png",
        "avatarUrl": "employee-avatars/emp-executive-director.png",
        "jobTitle": "المدير لتنفيذي للجمعية",
        "roleId": "role-executive",
        "branchId": "b-ahla-manil",
        "departmentId": "d-executive",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-executive-director",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-executive-secretary",
        "employeeCode": "AHS-002",
        "fullName": "يحيي جمال السبع",
        "phone": "PHONE_PLACEHOLDER_083",
        "email": "emp.demo083@ahla.local",
        "photoUrl": "employee-avatars/emp-executive-secretary.png",
        "avatarUrl": "employee-avatars/emp-executive-secretary.png",
        "jobTitle": "السكرتير التنفيذي + تكنولوجيا المعلومات (IT) والبرمجة",
        "roleId": "role-executive-secretary",
        "branchId": "b-ahla-manil",
        "departmentId": "d-executive",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-executive-secretary",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-direct-manager-01",
        "employeeCode": "AHS-003",
        "fullName": "محمد ابو عمار",
        "phone": "PHONE_PLACEHOLDER_084",
        "email": "emp.demo084@ahla.local",
        "photoUrl": "employee-avatars/emp-direct-manager-01.png",
        "avatarUrl": "employee-avatars/emp-direct-manager-01.png",
        "jobTitle": "مدير تشغيل 1",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-direct-manager-01",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-004",
        "employeeCode": "AHS-004",
        "fullName": "محمد عبدالعظيم محمد",
        "phone": "PHONE_PLACEHOLDER_072",
        "email": "emp.demo072@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-004.png",
        "avatarUrl": "employee-avatars/emp-xlsx-004.png",
        "jobTitle": "مسؤول اللجنة الطبية",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-01",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-004",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-hr-manager",
        "employeeCode": "AHS-005",
        "fullName": "بلال محمد الشاكر",
        "phone": "PHONE_PLACEHOLDER_046",
        "email": "emp.demo046@ahla.local",
        "photoUrl": "employee-avatars/emp-hr-manager.png",
        "avatarUrl": "employee-avatars/emp-hr-manager.png",
        "jobTitle": "مسؤول الموارد البشرية + الاعلام",
        "roleId": "role-hr",
        "branchId": "b-ahla-manil",
        "departmentId": "d-hr",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-hr-manager",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-direct-manager-06",
        "employeeCode": "AHS-006",
        "fullName": "ياسر فتحي نور الدين",
        "phone": "PHONE_PLACEHOLDER_082",
        "email": "emp.demo082@ahla.local",
        "photoUrl": "employee-avatars/emp-direct-manager-06.png",
        "avatarUrl": "employee-avatars/emp-direct-manager-06.png",
        "jobTitle": "مدير تشغيل 2",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-direct-manager-06",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-007",
        "employeeCode": "AHS-007",
        "fullName": "مصطفي فايد",
        "phone": "PHONE_PLACEHOLDER_014",
        "email": "emp.demo014@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-007.png",
        "avatarUrl": "employee-avatars/emp-xlsx-007.png",
        "jobTitle": "مدير الحسابات",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-007",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-direct-manager-02",
        "employeeCode": "AHS-008",
        "fullName": "حامد محمود العمدة",
        "phone": "PHONE_PLACEHOLDER_013",
        "email": "emp.demo013@ahla.local",
        "photoUrl": "employee-avatars/emp-direct-manager-02.png",
        "avatarUrl": "employee-avatars/emp-direct-manager-02.png",
        "jobTitle": "مسؤول لجنة أسرة كريمة",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-01",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-direct-manager-02",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-direct-manager-03",
        "employeeCode": "AHS-009",
        "fullName": "مصطفي احمد",
        "phone": "PHONE_PLACEHOLDER_075",
        "email": "emp.demo075@ahla.local",
        "photoUrl": "employee-avatars/emp-direct-manager-03.png",
        "avatarUrl": "employee-avatars/emp-direct-manager-03.png",
        "jobTitle": "ادارة اللوجيستك",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-direct-manager-03",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-010",
        "employeeCode": "AHS-010",
        "fullName": "محمد سيد",
        "phone": "PHONE_PLACEHOLDER_019",
        "email": "emp.demo019@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-010.png",
        "avatarUrl": "employee-avatars/emp-xlsx-010.png",
        "jobTitle": "موظف مشتريات",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-03",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-010",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-011",
        "employeeCode": "AHS-011",
        "fullName": "حاتم محمد سالم",
        "phone": "PHONE_PLACEHOLDER_074",
        "email": "emp.demo074@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-011.png",
        "avatarUrl": "employee-avatars/emp-xlsx-011.png",
        "jobTitle": "سائق العربية عزيزة",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-03",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-011",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-012",
        "employeeCode": "AHS-012",
        "fullName": "ربيع محمد ابو زيد",
        "phone": "PHONE_PLACEHOLDER_081",
        "email": "emp.demo081@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "سائق العربية مسك",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-03",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-012",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-013",
        "employeeCode": "AHS-013",
        "fullName": "طارق سيد إبراهيم",
        "phone": "PHONE_PLACEHOLDER_012",
        "email": "emp.demo012@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-013.png",
        "avatarUrl": "employee-avatars/emp-xlsx-013.png",
        "jobTitle": "مدير الحركة سائق + مطبخ المتععفين 2",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-03",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-013",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-014",
        "employeeCode": "AHS-014",
        "fullName": "عمار محمد عبدالباسط",
        "phone": "PHONE_PLACEHOLDER_078",
        "email": "emp.demo078@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "جرافيك ديزاينر",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-hr-manager",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-014",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-direct-manager-04",
        "employeeCode": "AHS-015",
        "fullName": "احمد محمد محجوب",
        "phone": "PHONE_PLACEHOLDER_047",
        "email": "emp.demo047@ahla.local",
        "photoUrl": "employee-avatars/emp-direct-manager-04.png",
        "avatarUrl": "employee-avatars/emp-direct-manager-04.png",
        "jobTitle": "مدير الشؤون الادارية",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-direct-manager-04",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-016",
        "employeeCode": "AHS-016",
        "fullName": "عبدالله حسين حافظ",
        "phone": "PHONE_PLACEHOLDER_076",
        "email": "emp.demo076@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-016.png",
        "avatarUrl": "employee-avatars/emp-xlsx-016.png",
        "jobTitle": "شؤون ادارية",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-04",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-016",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-017",
        "employeeCode": "AHS-017",
        "fullName": "عبد القادر جمال",
        "phone": "PHONE_PLACEHOLDER_045",
        "email": "emp.demo045@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-017.png",
        "avatarUrl": "employee-avatars/emp-xlsx-017.png",
        "jobTitle": "شؤون إدارية",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-04",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-017",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-018",
        "employeeCode": "AHS-018",
        "fullName": "هاني احمد نصير",
        "phone": "PHONE_PLACEHOLDER_018",
        "email": "emp.demo018@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-018.png",
        "avatarUrl": "employee-avatars/emp-xlsx-018.png",
        "jobTitle": "مسؤول المشروعات و طلاب العلم",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-01",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-018",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-direct-manager-05",
        "employeeCode": "AHS-019",
        "fullName": "يوسف رسمي شعبان",
        "phone": "PHONE_PLACEHOLDER_007",
        "email": "emp.demo007@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "المشرف الفني لمجمع منيل شيحة",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-direct-manager-05",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-020",
        "employeeCode": "AHS-020",
        "fullName": "اسماعيل عبدالله",
        "phone": "PHONE_PLACEHOLDER_073",
        "email": "emp.demo073@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-020.png",
        "avatarUrl": "employee-avatars/emp-xlsx-020.png",
        "jobTitle": "موظف بالمجمع",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-05",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-020",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-021",
        "employeeCode": "AHS-021",
        "fullName": "عبدالرحمن حسين مرعي",
        "phone": "PHONE_PLACEHOLDER_079",
        "email": "emp.demo079@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-021.png",
        "avatarUrl": "employee-avatars/emp-xlsx-021.png",
        "jobTitle": "موظف لجنة أسرة كريمة",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-02",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-021",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-022",
        "employeeCode": "AHS-022",
        "fullName": "محمد عبده مزار",
        "phone": "PHONE_PLACEHOLDER_011",
        "email": "emp.demo011@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "طباخ بمجمع أحلى شباب",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-05",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-022",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-023",
        "employeeCode": "AHS-023",
        "fullName": "حسام عفيفي جمعة",
        "phone": "PHONE_PLACEHOLDER_009",
        "email": "emp.demo009@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "موظف بالمجمع",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-05",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-023",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-024",
        "employeeCode": "AHS-024",
        "fullName": "محمد الاندونيسي",
        "phone": "PHONE_PLACEHOLDER_077",
        "email": "emp.demo077@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-024.png",
        "avatarUrl": "employee-avatars/emp-xlsx-024.png",
        "jobTitle": "مسؤول الدعايا",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-06",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-024",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-025",
        "employeeCode": "AHS-025",
        "fullName": "ياسين طارق الباسل",
        "phone": "PHONE_PLACEHOLDER_080",
        "email": "emp.demo080@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "مسؤول الدعايا",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-06",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-025",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-026",
        "employeeCode": "AHS-026",
        "fullName": "عبد العزيز طارق الباسل",
        "phone": "PHONE_PLACEHOLDER_008",
        "email": "emp.demo008@ahla.local",
        "photoUrl": "employee-avatars/emp-xlsx-026.png",
        "avatarUrl": "employee-avatars/emp-xlsx-026.png",
        "jobTitle": "مسؤول سفير + مطيخ المتعففين 3",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-026",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-027",
        "employeeCode": "AHS-027",
        "fullName": "محمد عبد المنعم",
        "phone": "PHONE_PLACEHOLDER_015",
        "email": "emp.demo015@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "مسؤول الاستكشاف",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-executive-director",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-027",
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "emp-xlsx-028",
        "employeeCode": "AHS-028",
        "fullName": "عبداالله نصر",
        "phone": "PHONE_PLACEHOLDER_020",
        "email": "emp.demo020@ahla.local",
        "photoUrl": "",
        "avatarUrl": "",
        "jobTitle": "أدارة المتطوعين",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "managerEmployeeId": "emp-direct-manager-06",
        "status": "ACTIVE",
        "isDeleted": false,
        "hireDate": "2026-05-02",
        "userId": "u-xlsx-028",
        "rosterSource": "بيانات الموظفين.xlsx"
    }
],
  users: [
    {
        "id": "u-executive-director",
        "employeeId": "emp-executive-director",
        "name": "الشيخ محمد يوسف",
        "fullName": "الشيخ محمد يوسف",
        "email": "emp.demo010@ahla.local",
        "phone": "PHONE_PLACEHOLDER_010",
        "username": "PHONE_PLACEHOLDER_010",
        "avatarUrl": "employee-avatars/emp-executive-director.png",
        "photoUrl": "employee-avatars/emp-executive-director.png",
        "password": "PHONE_PLACEHOLDER_010",
        "roleId": "role-executive",
        "branchId": "b-ahla-manil",
        "departmentId": "d-executive",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-executive-secretary",
        "employeeId": "emp-executive-secretary",
        "name": "يحيي جمال السبع",
        "fullName": "يحيي جمال السبع",
        "email": "emp.demo083@ahla.local",
        "phone": "PHONE_PLACEHOLDER_083",
        "username": "PHONE_PLACEHOLDER_083",
        "avatarUrl": "employee-avatars/emp-executive-secretary.png",
        "photoUrl": "employee-avatars/emp-executive-secretary.png",
        "password": "PHONE_PLACEHOLDER_083",
        "roleId": "role-executive-secretary",
        "branchId": "b-ahla-manil",
        "departmentId": "d-executive",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-direct-manager-01",
        "employeeId": "emp-direct-manager-01",
        "name": "محمد ابو عمار",
        "fullName": "محمد ابو عمار",
        "email": "emp.demo084@ahla.local",
        "phone": "PHONE_PLACEHOLDER_084",
        "username": "PHONE_PLACEHOLDER_084",
        "avatarUrl": "employee-avatars/emp-direct-manager-01.png",
        "photoUrl": "employee-avatars/emp-direct-manager-01.png",
        "password": "PHONE_PLACEHOLDER_084",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-004",
        "employeeId": "emp-xlsx-004",
        "name": "محمد عبدالعظيم محمد",
        "fullName": "محمد عبدالعظيم محمد",
        "email": "emp.demo072@ahla.local",
        "phone": "PHONE_PLACEHOLDER_072",
        "username": "PHONE_PLACEHOLDER_072",
        "avatarUrl": "employee-avatars/emp-xlsx-004.png",
        "photoUrl": "employee-avatars/emp-xlsx-004.png",
        "password": "PHONE_PLACEHOLDER_072",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-hr-manager",
        "employeeId": "emp-hr-manager",
        "name": "بلال محمد الشاكر",
        "fullName": "بلال محمد الشاكر",
        "email": "emp.demo046@ahla.local",
        "phone": "PHONE_PLACEHOLDER_046",
        "username": "PHONE_PLACEHOLDER_046",
        "avatarUrl": "employee-avatars/emp-hr-manager.png",
        "photoUrl": "employee-avatars/emp-hr-manager.png",
        "password": "PHONE_PLACEHOLDER_046",
        "roleId": "role-hr",
        "branchId": "b-ahla-manil",
        "departmentId": "d-hr",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-direct-manager-06",
        "employeeId": "emp-direct-manager-06",
        "name": "ياسر فتحي نور الدين",
        "fullName": "ياسر فتحي نور الدين",
        "email": "emp.demo082@ahla.local",
        "phone": "PHONE_PLACEHOLDER_082",
        "username": "PHONE_PLACEHOLDER_082",
        "avatarUrl": "employee-avatars/emp-direct-manager-06.png",
        "photoUrl": "employee-avatars/emp-direct-manager-06.png",
        "password": "PHONE_PLACEHOLDER_082",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-007",
        "employeeId": "emp-xlsx-007",
        "name": "مصطفي فايد",
        "fullName": "مصطفي فايد",
        "email": "emp.demo014@ahla.local",
        "phone": "PHONE_PLACEHOLDER_014",
        "username": "PHONE_PLACEHOLDER_014",
        "avatarUrl": "employee-avatars/emp-xlsx-007.png",
        "photoUrl": "employee-avatars/emp-xlsx-007.png",
        "password": "PHONE_PLACEHOLDER_014",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-direct-manager-02",
        "employeeId": "emp-direct-manager-02",
        "name": "حامد محمود العمدة",
        "fullName": "حامد محمود العمدة",
        "email": "emp.demo013@ahla.local",
        "phone": "PHONE_PLACEHOLDER_013",
        "username": "PHONE_PLACEHOLDER_013",
        "avatarUrl": "employee-avatars/emp-direct-manager-02.png",
        "photoUrl": "employee-avatars/emp-direct-manager-02.png",
        "password": "PHONE_PLACEHOLDER_013",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-direct-manager-03",
        "employeeId": "emp-direct-manager-03",
        "name": "مصطفي احمد",
        "fullName": "مصطفي احمد",
        "email": "emp.demo075@ahla.local",
        "phone": "PHONE_PLACEHOLDER_075",
        "username": "PHONE_PLACEHOLDER_075",
        "avatarUrl": "employee-avatars/emp-direct-manager-03.png",
        "photoUrl": "employee-avatars/emp-direct-manager-03.png",
        "password": "PHONE_PLACEHOLDER_075",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-010",
        "employeeId": "emp-xlsx-010",
        "name": "محمد سيد",
        "fullName": "محمد سيد",
        "email": "emp.demo019@ahla.local",
        "phone": "PHONE_PLACEHOLDER_019",
        "username": "PHONE_PLACEHOLDER_019",
        "avatarUrl": "employee-avatars/emp-xlsx-010.png",
        "photoUrl": "employee-avatars/emp-xlsx-010.png",
        "password": "PHONE_PLACEHOLDER_019",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-011",
        "employeeId": "emp-xlsx-011",
        "name": "حاتم محمد سالم",
        "fullName": "حاتم محمد سالم",
        "email": "emp.demo074@ahla.local",
        "phone": "PHONE_PLACEHOLDER_074",
        "username": "PHONE_PLACEHOLDER_074",
        "avatarUrl": "employee-avatars/emp-xlsx-011.png",
        "photoUrl": "employee-avatars/emp-xlsx-011.png",
        "password": "PHONE_PLACEHOLDER_074",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-012",
        "employeeId": "emp-xlsx-012",
        "name": "ربيع محمد ابو زيد",
        "fullName": "ربيع محمد ابو زيد",
        "email": "emp.demo081@ahla.local",
        "phone": "PHONE_PLACEHOLDER_081",
        "username": "PHONE_PLACEHOLDER_081",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_081",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-013",
        "employeeId": "emp-xlsx-013",
        "name": "طارق سيد إبراهيم",
        "fullName": "طارق سيد إبراهيم",
        "email": "emp.demo012@ahla.local",
        "phone": "PHONE_PLACEHOLDER_012",
        "username": "PHONE_PLACEHOLDER_012",
        "avatarUrl": "employee-avatars/emp-xlsx-013.png",
        "photoUrl": "employee-avatars/emp-xlsx-013.png",
        "password": "PHONE_PLACEHOLDER_012",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-014",
        "employeeId": "emp-xlsx-014",
        "name": "عمار محمد عبدالباسط",
        "fullName": "عمار محمد عبدالباسط",
        "email": "emp.demo078@ahla.local",
        "phone": "PHONE_PLACEHOLDER_078",
        "username": "PHONE_PLACEHOLDER_078",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_078",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-direct-manager-04",
        "employeeId": "emp-direct-manager-04",
        "name": "احمد محمد محجوب",
        "fullName": "احمد محمد محجوب",
        "email": "emp.demo047@ahla.local",
        "phone": "PHONE_PLACEHOLDER_047",
        "username": "PHONE_PLACEHOLDER_047",
        "avatarUrl": "employee-avatars/emp-direct-manager-04.png",
        "photoUrl": "employee-avatars/emp-direct-manager-04.png",
        "password": "PHONE_PLACEHOLDER_047",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-016",
        "employeeId": "emp-xlsx-016",
        "name": "عبدالله حسين حافظ",
        "fullName": "عبدالله حسين حافظ",
        "email": "emp.demo076@ahla.local",
        "phone": "PHONE_PLACEHOLDER_076",
        "username": "PHONE_PLACEHOLDER_076",
        "avatarUrl": "employee-avatars/emp-xlsx-016.png",
        "photoUrl": "employee-avatars/emp-xlsx-016.png",
        "password": "PHONE_PLACEHOLDER_076",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-017",
        "employeeId": "emp-xlsx-017",
        "name": "عبد القادر جمال",
        "fullName": "عبد القادر جمال",
        "email": "emp.demo045@ahla.local",
        "phone": "PHONE_PLACEHOLDER_045",
        "username": "PHONE_PLACEHOLDER_045",
        "avatarUrl": "employee-avatars/emp-xlsx-017.png",
        "photoUrl": "employee-avatars/emp-xlsx-017.png",
        "password": "PHONE_PLACEHOLDER_045",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-018",
        "employeeId": "emp-xlsx-018",
        "name": "هاني احمد نصير",
        "fullName": "هاني احمد نصير",
        "email": "emp.demo018@ahla.local",
        "phone": "PHONE_PLACEHOLDER_018",
        "username": "PHONE_PLACEHOLDER_018",
        "avatarUrl": "employee-avatars/emp-xlsx-018.png",
        "photoUrl": "employee-avatars/emp-xlsx-018.png",
        "password": "PHONE_PLACEHOLDER_018",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-direct-manager-05",
        "employeeId": "emp-direct-manager-05",
        "name": "يوسف رسمي شعبان",
        "fullName": "يوسف رسمي شعبان",
        "email": "emp.demo007@ahla.local",
        "phone": "PHONE_PLACEHOLDER_007",
        "username": "PHONE_PLACEHOLDER_007",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_007",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-020",
        "employeeId": "emp-xlsx-020",
        "name": "اسماعيل عبدالله",
        "fullName": "اسماعيل عبدالله",
        "email": "emp.demo073@ahla.local",
        "phone": "PHONE_PLACEHOLDER_073",
        "username": "PHONE_PLACEHOLDER_073",
        "avatarUrl": "employee-avatars/emp-xlsx-020.png",
        "photoUrl": "employee-avatars/emp-xlsx-020.png",
        "password": "PHONE_PLACEHOLDER_073",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-021",
        "employeeId": "emp-xlsx-021",
        "name": "عبدالرحمن حسين مرعي",
        "fullName": "عبدالرحمن حسين مرعي",
        "email": "emp.demo079@ahla.local",
        "phone": "PHONE_PLACEHOLDER_079",
        "username": "PHONE_PLACEHOLDER_079",
        "avatarUrl": "employee-avatars/emp-xlsx-021.png",
        "photoUrl": "employee-avatars/emp-xlsx-021.png",
        "password": "PHONE_PLACEHOLDER_079",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-022",
        "employeeId": "emp-xlsx-022",
        "name": "محمد عبده مزار",
        "fullName": "محمد عبده مزار",
        "email": "emp.demo011@ahla.local",
        "phone": "PHONE_PLACEHOLDER_011",
        "username": "PHONE_PLACEHOLDER_011",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_011",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-023",
        "employeeId": "emp-xlsx-023",
        "name": "حسام عفيفي جمعة",
        "fullName": "حسام عفيفي جمعة",
        "email": "emp.demo009@ahla.local",
        "phone": "PHONE_PLACEHOLDER_009",
        "username": "PHONE_PLACEHOLDER_009",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_009",
        "roleId": "role-employee",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-operations",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-024",
        "employeeId": "emp-xlsx-024",
        "name": "محمد الاندونيسي",
        "fullName": "محمد الاندونيسي",
        "email": "emp.demo077@ahla.local",
        "phone": "PHONE_PLACEHOLDER_077",
        "username": "PHONE_PLACEHOLDER_077",
        "avatarUrl": "employee-avatars/emp-xlsx-024.png",
        "photoUrl": "employee-avatars/emp-xlsx-024.png",
        "password": "PHONE_PLACEHOLDER_077",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-025",
        "employeeId": "emp-xlsx-025",
        "name": "ياسين طارق الباسل",
        "fullName": "ياسين طارق الباسل",
        "email": "emp.demo080@ahla.local",
        "phone": "PHONE_PLACEHOLDER_080",
        "username": "PHONE_PLACEHOLDER_080",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_080",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-026",
        "employeeId": "emp-xlsx-026",
        "name": "عبد العزيز طارق الباسل",
        "fullName": "عبد العزيز طارق الباسل",
        "email": "emp.demo008@ahla.local",
        "phone": "PHONE_PLACEHOLDER_008",
        "username": "PHONE_PLACEHOLDER_008",
        "avatarUrl": "employee-avatars/emp-xlsx-026.png",
        "photoUrl": "employee-avatars/emp-xlsx-026.png",
        "password": "PHONE_PLACEHOLDER_008",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-027",
        "employeeId": "emp-xlsx-027",
        "name": "محمد عبد المنعم",
        "fullName": "محمد عبد المنعم",
        "email": "emp.demo015@ahla.local",
        "phone": "PHONE_PLACEHOLDER_015",
        "username": "PHONE_PLACEHOLDER_015",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_015",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    },
    {
        "id": "u-xlsx-028",
        "employeeId": "emp-xlsx-028",
        "name": "عبداالله نصر",
        "fullName": "عبداالله نصر",
        "email": "emp.demo020@ahla.local",
        "phone": "PHONE_PLACEHOLDER_020",
        "username": "PHONE_PLACEHOLDER_020",
        "avatarUrl": "",
        "photoUrl": "",
        "password": "PHONE_PLACEHOLDER_020",
        "roleId": "role-manager",
        "branchId": "b-ahla-manil",
        "departmentId": "d-field-management",
        "governorateId": "gov-giza",
        "complexId": "cx-ahla-manil",
        "status": "ACTIVE",
        "temporaryPassword": false,
        "mustChangePassword": false,
        "passkeyEnabled": false,
        "failedLogins": 0,
        "lastLoginAt": "",
        "phoneLoginOnly": true,
        "rosterSource": "بيانات الموظفين.xlsx"
    }
],
  attendanceEvents: [
    { id: "att-001", employeeId: "emp-direct-manager-04", type: "PRESENT", eventAt: "2026-04-26T08:02:00", source: "جهاز البصمة", verificationStatus: "verified", geofenceStatus: "inside_branch", requiresReview: false, riskFlags: [] },
    { id: "att-002", employeeId: "emp-direct-manager-03", type: "PRESENT", eventAt: "2026-04-26T08:08:00", source: "تطبيق الويب", verificationStatus: "verified", geofenceStatus: "inside_branch", requiresReview: false, riskFlags: [] },
    { id: "att-003", employeeId: "emp-worker-001", type: "LATE", eventAt: "2026-04-26T14:17:00", source: "جهاز البصمة", verificationStatus: "verified", geofenceStatus: "inside_branch", requiresReview: true, riskFlags: ["late"] },
    { id: "att-004", employeeId: "emp-worker-001", type: "PRESENT", eventAt: "2026-04-26T08:00:00", source: "تطبيق الويب", verificationStatus: "verified", geofenceStatus: "inside_branch", requiresReview: false, riskFlags: [] },
    { id: "att-005", employeeId: "emp-worker-001", type: "MISSION", eventAt: "2026-04-26T08:30:00", source: "مأمورية", verificationStatus: "verified", geofenceStatus: "inside_mission", requiresReview: false, riskFlags: [] },
    { id: "att-006", employeeId: "emp-worker-001", type: "PRESENT", eventAt: "2026-04-26T09:11:00", source: "جهاز البصمة", verificationStatus: "verified", geofenceStatus: "inside_branch", requiresReview: false, riskFlags: [] },
    { id: "att-007", employeeId: "emp-worker-001", type: "ABSENT", eventAt: "2026-04-26T09:30:00", source: "النظام", verificationStatus: "not_checked", geofenceStatus: "unknown", requiresReview: false, riskFlags: [] },
  ],
  attendanceDaily: [
    { id: "day-001", employeeId: "emp-direct-manager-04", date: "2026-04-26", status: "PRESENT", lateMinutes: 0, workMinutes: 480, requiresReview: false },
    { id: "day-002", employeeId: "emp-direct-manager-03", date: "2026-04-26", status: "PRESENT", lateMinutes: 0, workMinutes: 470, requiresReview: false },
    { id: "day-003", employeeId: "emp-worker-001", date: "2026-04-26", status: "LATE", lateMinutes: 17, workMinutes: 430, requiresReview: true },
    { id: "day-004", employeeId: "emp-worker-001", date: "2026-04-26", status: "LEAVE", lateMinutes: 0, workMinutes: 0, requiresReview: false },
    { id: "day-005", employeeId: "emp-worker-001", date: "2026-04-26", status: "MISSION", lateMinutes: 0, workMinutes: 450, requiresReview: false },
  ],
  missions: [
    { id: "mis-001", employeeId: "emp-worker-001", title: "صيانة شبكة فرع الجيزة", destinationName: "فرع الجيزة", plannedStart: "2026-04-26T09:00", plannedEnd: "2026-04-26T14:00", status: "APPROVED", approvalStatus: "approved", workflow: [{ at: "2026-04-25T12:20:00", by: "مدير النظام", action: "created" }, { at: "2026-04-25T13:00:00", by: "مدير النظام", action: "approved" }], createdAt: "2026-04-25T12:20:00" },
    { id: "mis-002", employeeId: "emp-worker-001", title: "زيارة عميل رئيسي", destinationName: "مدينة نصر", plannedStart: "2026-04-27T10:00", plannedEnd: "2026-04-27T13:00", status: "PENDING", approvalStatus: "pending", workflow: [{ at: "2026-04-26T10:10:00", by: "محمود خالد", action: "created" }], createdAt: "2026-04-26T10:10:00" },
  ],
  leaves: [
    { id: "lv-001", employeeId: "emp-direct-manager-04", leaveType: { name: "اعتيادية" }, startDate: "2026-04-28", endDate: "2026-04-30", reason: "ظروف عائلية", status: "PENDING", workflow: [{ at: "2026-04-24T11:00:00", by: "موظف إداري", action: "created" }], createdAt: "2026-04-24T11:00:00" },
    { id: "lv-002", employeeId: "emp-worker-001", leaveType: { name: "مرضية" }, startDate: "2026-04-26", endDate: "2026-04-27", reason: "متابعة طبية", status: "APPROVED", workflow: [{ at: "2026-04-25T09:30:00", by: "منى سامي", action: "created" }, { at: "2026-04-25T10:15:00", by: "أحمد محمد", action: "approved" }], createdAt: "2026-04-25T09:30:00" },
  ],
  exceptions: [
    { id: "exc-001", title: "تأخير بعذر", reason: "ازدحام مروري", employeeId: "emp-worker-001", status: "APPROVED", workflow: [{ at: "2026-04-26T09:40:00", by: "محمود خالد", action: "created" }, { at: "2026-04-26T10:00:00", by: "سارة علي", action: "approved" }], createdAt: "2026-04-26T09:40:00" },
    { id: "exc-002", title: "نسيان بصمة انصراف", reason: "نسيان تسجيل الانصراف", employeeId: "emp-worker-001", status: "PENDING", workflow: [{ at: "2026-04-25T18:10:00", by: "نورهان عادل", action: "created" }], createdAt: "2026-04-25T18:10:00" },
  ],
  locations: [
    { id: "loc-001", name: "فرع القاهرة", employeeId: "emp-direct-manager-04", status: "ACTIVE", date: "2026-04-26T08:00:00" },
    { id: "loc-002", name: "فرع الجيزة", employeeId: "emp-worker-001", status: "ACTIVE", date: "2026-04-26T08:30:00" },
    { id: "loc-003", name: "موقع عميل مدينة نصر", employeeId: "emp-worker-001", status: "VISITED", date: "2026-04-26T11:15:00" },
  ],
  locationRequests: [
    { id: "locreq-001", employeeId: "emp-worker-001", purpose: "فتح الموقع وإرسال اللوكيشن المباشر", requestReason: "", status: "PENDING", requestedAt: "2026-04-26T11:00:00", expiresAt: "2026-04-26T11:45:00" }
  ],
  kpiPolicy: {
    evaluationStartDay: 20,
    evaluationEndDay: 25,
    submissionDeadlineDay: 25,
    lateReviewGraceDays: 3,
    hardCloseAfterDay: 28,
    remindersEnabled: true,
    meetingRequired: true,
    description: "يبدأ تقييم الأداء من يوم 20 حتى 25 من كل شهر من خلال جلسة بين الموظف ومديره المباشر. آخر موعد لتسليم التقييمات يوم 25.",
  },
  kpiCycles: [
    { id: "kpi-cycle-current", name: "دورة تقييم الأداء الشهرية", periodType: "monthly", startsOn: "2026-04-20", endsOn: "2026-04-25", status: "PENDING", dueOn: "2026-04-25", createdAt: "2026-04-20T08:00:00" },
  ],
  kpiCriteria: [
    { id: "kc-target", code: "TARGET", name: "تحقيق الأهداف", description: "مدى تحقيق الأهداف المتفق عليها للموظف خلال الشهر.", maxScore: 40, weight: 40, sortOrder: 1, parentCode: "PERFORMANCE", scoringType: "manual" },
    { id: "kc-efficiency", code: "TASK_EFFICIENCY", name: "الكفاءة في أداء المهام", description: "جودة التنفيذ، سرعة الإنجاز، ودقة المتابعة.", maxScore: 20, weight: 20, sortOrder: 2, parentCode: "PERFORMANCE", scoringType: "manual" },
    { id: "kc-attendance", code: "ATTENDANCE_COMMITMENT", name: "الالتزام بمواعيد العمل حضورًا وانصرافًا", description: "جزء من السلوكيات والانضباط ويُحسب من بيانات الحضور مع إمكانية مراجعة المدير.", maxScore: 20, weight: 20, sortOrder: 3, parentCode: "BEHAVIOR", scoringType: "auto_manual" },
    { id: "kc-conduct", code: "CONDUCT", name: "حسن التعامل والسلوك مع الزملاء والمديرين", description: "التعاون، الاحترام، والالتزام بسلوك مهني داخل بيئة العمل.", maxScore: 5, weight: 5, sortOrder: 4, parentCode: "BEHAVIOR", scoringType: "manual" },
    { id: "kc-prayer", code: "MOSQUE_PRAYER", name: "الالتزام بالصلاة في المسجد", description: "تقييم التزام الموظف بهذا السلوك المؤسسي خلال الشهر.", maxScore: 5, weight: 5, sortOrder: 5, parentCode: "BEHAVIOR", scoringType: "manual" },
    { id: "kc-quran", code: "QURAN_CIRCLE", name: "حضور حلقة الشيخ وليد يوسف الأسبوعية", description: "حضور حلقة الشيخ وليد يوسف الأسبوعية لتدريس القرآن والتجويد.", maxScore: 5, weight: 5, sortOrder: 6, parentCode: "BEHAVIOR", scoringType: "manual" },
    { id: "kc-initiatives", code: "INITIATIVES_DONATIONS", name: "المشاركة في التبرعات والمبادرات", description: "مشاركة إيجابية في المبادرات والتبرعات المعتمدة.", maxScore: 5, weight: 5, sortOrder: 7, parentCode: "INITIATIVES", scoringType: "manual" },
  ],
  kpiEvaluations: [
    { id: "kpie-001", cycleId: "kpi-cycle-current", employeeId: "emp-direct-manager-03", managerEmployeeId: "emp-direct-manager-04", evaluationDate: "2026-04-22", targetScore: 34, efficiencyScore: 17, attendanceScore: 19, conductScore: 5, prayerScore: 4, quranCircleScore: 5, initiativesScore: 4, totalScore: 88, grade: "B", status: "SUBMITTED", managerNotes: "أداء قوي ويحتاج تركيز أكبر في إغلاق المتابعات.", employeeNotes: "تمت جلسة التقييم مع المدير المباشر.", createdAt: "2026-04-22T11:00:00", submittedAt: "2026-04-22T11:30:00" },
  ],
  kpiSummaries: [],
  disputeCommittee: {
    "members": [
        "الشيخ محمد يوسف",
        "يحيي جمال السبع",
        "محمد ابو عمار",
        "بلال محمد الشاكر",
        "ياسر فتحي نور الدين"
    ],
    "employeeIds": [
        "emp-executive-director",
        "emp-executive-secretary",
        "emp-direct-manager-01",
        "emp-hr-manager",
        "emp-direct-manager-02"
    ],
    "executiveEscalationTo": "الشيخ محمد يوسف",
    "executiveSecretaryEmployeeId": "emp-executive-secretary",
    "mandate": "لجنة حل المشاكل والخلافات تراجع الشكاوى والخلافات الداخلية، وتستطيع التصعيد للسكرتير التنفيذي والمدير التنفيذي مع حفظ كل القرارات والإجراءات.",
    "escalationRules": [
        "عدم قدرة اللجنة على الحل",
        "المشكلة طارئة وتحتاج قرارًا تنفيذيًا",
        "تكرار الخلاف أو تأثيره على سير العمل"
    ]
},
  disputeCases: [
    { id: "disp-001", title: "تداخل مسؤوليات بين التشغيل والمبيعات", employeeId: "emp-direct-manager-03", category: "إداري", priority: "MEDIUM", description: "طلب تنظيم حدود المسؤولية بين فريقين.", status: "IN_REVIEW", assignedCommittee: ["مدير مباشر ثالث", "مدير مباشر ثانٍ", "مدير مباشر أول", "السكرتير التنفيذي", "المدير التنفيذي"], committeeDecision: "تحت المراجعة", escalatedToExecutive: false, createdAt: "2026-04-26T12:20:00" },
  ],
  notifications: [
    { id: "not-001", title: "طلب إجازة جديد من موظف إداري", body: "طلب اعتيادي يحتاج مراجعة.", status: "UNREAD", isRead: false, type: "INFO", createdAt: "2026-04-26T10:00:00" },
    { id: "not-002", title: "تقرير الحضور اليومي جاهز", body: "يمكن تحميل التقرير من صفحة التقارير.", status: "READ", isRead: true, type: "SUCCESS", createdAt: "2026-04-26T09:00:00" },
  ],
  integrationSettings: [
    { id: "int-webauthn", key: "webauthn", name: "WebAuthn/FIDO2", provider: "browser", enabled: true, status: "READY_ON_HTTPS", notes: "يعمل على localhost أو HTTPS مع Touch ID / Face ID / Windows Hello / YubiKey" },
    { id: "int-push", key: "push", name: "Push Notifications", provider: "web-push", enabled: true, status: "READY", notes: "يتطلب VAPID عند تشغيل Backend" },
    { id: "int-access", key: "access_control", name: "Access Control", provider: "turnstile-door-api", enabled: false, status: "HARDWARE_REQUIRED", notes: "يتطلب جهاز بوابة أو API للأبواب الذكية" },
  ],
  passkeyCredentials: [],
  pushSubscriptions: [],
  offlineQueue: [],
  reportSchedules: [],
  accessControlEvents: [],
  credentialVault: [],
  reports: [
    { id: "rep-001", title: "تقرير حضور اليوم", reportKey: "attendance", format: "csv", status: "COMPLETED", createdAt: "2026-04-26T11:30:00" },
  ],
  attachments: [],
  auditLogs: [
    { id: "audit-001", action: "system.seed", entityType: "system", entityId: "seed", actor: "System", beforeData: null, afterData: { version: 5 }, createdAt: "2026-04-26T08:00:00" },
  ],
  settings: [
    { id: "set-001", key: "company.name", value: "مجمع منيل شيحة", scope: "company" },
    { id: "set-002", key: "workday.start", value: "09:00", scope: "attendance" },
    { id: "set-003", key: "workday.end", value: "17:00", scope: "attendance" },
    { id: "set-004", key: "lateGraceMinutes", value: 15, scope: "attendance" },
    { id: "set-005", key: "geo.enabled", value: true, scope: "security" },
    { id: "set-006", key: "approval.managerFirst", value: true, scope: "workflow" },
    { id: "set-007", key: "workday.weekend", value: ["FRI"], scope: "attendance" },
    { id: "set-008", key: "leave.defaultAnnualDays", value: 21, scope: "leave" },
    { id: "set-009", key: "documents.expiryAlertDays", value: 30, scope: "documents" },
    { id: "set-010", key: "security.requireDeviceApproval", value: true, scope: "security" },
  ],
  tasks: [
    { id: "task-001", title: "مراجعة طلبات الإجازات المعلقة", description: "مراجعة كل الطلبات القديمة أكثر من 48 ساعة وإغلاقها بقرار واضح.", employeeId: "emp-executive-secretary", assignedByEmployeeId: "emp-executive-director", priority: "HIGH", status: "OPEN", dueDate: "2026-04-30", createdAt: "2026-04-26T10:00:00" },
    { id: "task-002", title: "تجهيز تقرير الحضور الشهري", description: "إعداد تقرير PDF/Excel وتسليمه للمدير التنفيذي.", employeeId: "emp-executive-secretary", assignedByEmployeeId: "emp-executive-director", priority: "MEDIUM", status: "IN_PROGRESS", dueDate: "2026-04-30", createdAt: "2026-04-26T10:20:00" },
  ],
  employeeDocuments: [
    { id: "doc-001", employeeId: "emp-executive-secretary", title: "بطاقة الرقم القومي", documentType: "ID_CARD", status: "ACTIVE", fileName: "", fileUrl: "", expiresOn: "2027-12-31", notes: "مثال داخلي لتتبع المستندات.", createdAt: "2026-04-26T09:00:00" },
  ],
  leaveBalances: [
    { id: "lb-executive-secretary", employeeId: "emp-executive-secretary", annualTotal: 21, casualTotal: 7, sickTotal: 15, usedDays: 0, remainingDays: 28, updatedAt: "2026-04-26T09:00:00" },
  ],
  announcementReads: [],
  policyAcknowledgements: [],
  workflowEscalations: [],
  attendanceAlerts: [],
  dailyReports: [
    { id: "dr-001", employeeId: "emp-executive-secretary", reportDate: "2026-04-29", achievements: "استكمال تطوير نظام الموارد البشرية وتجهيز خطة التشغيل.", blockers: "يحتاج تفعيل Supabase الحقيقي لاختبار Live.", tomorrowPlan: "مراجعة الصلاحيات وتجربة المستخدمين.", supportNeeded: "بيانات الدخول النهائية للموظفين.", mood: "GOOD", status: "SUBMITTED", createdAt: "2026-04-29T09:00:00" }
  ],
  smartAlerts: [],
  importBatches: [],
  approvalChains: [],
  systemRunbooks: [
    { id: "runbook-001", title: "تشغيل النظام أول مرة", category: "PRODUCTION", steps: ["تطبيق كل SQL patches", "نشر Edge Functions", "تفعيل supabase-config.js", "تشغيل Health Check"], status: "ACTIVE" }
  ],
  meta: { version: 12, orgProfile: "ahla-shabab-manil-shiha-v2", updatedAt: "2026-04-29T17:10:00" },
};

const importedRoster = []

for (const [suffix, fullName, phone, jobTitle, hireDate, preferredEmail, rosterRoleId = "role-employee", rosterDepartmentId = "d-ops"] of importedRoster) {
  const id = `emp-xlsx-${suffix}`;
  const userId = `u-xlsx-${suffix}`;
  const email = preferredEmail || `emp.${phone}@ahla-shabab.org`;
  if (!seedDatabase.employees.some((employee) => employee.id === id || employee.phone === phone)) {
    seedDatabase.employees.push({
      id,
      fullName,
      phone,
      email,
      photoUrl: "",
      jobTitle,
      roleId: rosterRoleId,
      branchId: "b-ahla-manil",
      departmentId: rosterDepartmentId,
      governorateId: "gov-giza",
      complexId: "cx-ahla-manil",
      managerEmployeeId: "",
      status: "ACTIVE",
      isDeleted: false,
      hireDate,
      userId,
    });
  }
  if (!seedDatabase.users.some((user) => user.id === userId || user.phone === phone)) {
    seedDatabase.users.push({
      id: userId,
      name: fullName,
      fullName,
      email,
      phone,
      password: "LocalLoginDisabled#RotateInSupabase2026!",
      roleId: rosterRoleId,
      employeeId: id,
      branchId: "b-ahla-manil",
      departmentId: rosterDepartmentId,
      governorateId: "gov-giza",
      complexId: "cx-ahla-manil",
      status: "ACTIVE",
      temporaryPassword: true,
      mustChangePassword: true,
      passkeyEnabled: false,
      failedLogins: 0,
      lastLoginAt: "",
    });
  }
}

seedDatabase.meta.version = 12;
seedDatabase.meta.updatedAt = "2026-04-29T18:30:00";
